services:

  zookeeper:
    image: bitnami/zookeeper
    ports: ["2181:2181"]
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    depends_on: [zookeeper]

  kafka_init:
    image: confluentinc/cp-kafka
    depends_on: [kafka]
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic weather_data --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --list
      "

  kafka_weather_producer:
    build: data-ingestion/.
    depends_on: [kafka]
    env_file: [.env]
    environment:
      OPEN_WEATHER_MAP_API_KEY: ${OPEN_WEATHER_MAP_API_KEY}
      CITY_NAME: Warsaw
      KAFKA_TOPIC: ${KAFKA_TOPIC}

  spark:
    image: bitnami/spark
    environment:
      SPARK_MODE: master
    ports: ["7077:7077", "8080:8080"]

  spark-worker:
    image: bitnami/spark
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
    depends_on: [spark]

  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    environment:
      CLUSTER_NAME: test
    volumes: [hdfs-namenode:/hadoop/dfs/name]
    ports: ["9000:9000"]

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    environment:
      CLUSTER_NAME: test
      CORE_CONF_fs_defaultFS: hdfs://hdfs-namenode:9000
    volumes: [hdfs-datanode:/hadoop/dfs/data]
    depends_on: [hdfs-namenode]

  hive:
    image: bde2020/hive:2.3.2-postgresql-metastore
    environment:
      HIVE_METASTORE_URI: thrift://hive-metastore:9083
      HIVE_CONF_hive_exec_scratchdir: /tmp/hive
      HIVE_CONF_hive_log_dir: /tmp/hive
    ports: ["10000:10000"]
    depends_on: [hdfs-namenode, hdfs-datanode]

volumes:
  hdfs-namenode:
    external: false
  hdfs-datanode:
    external: false